FROM docker.io/golang:1.24.2-alpine3.21 as base
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY utils ./utils
COPY queue ./queue
ENV TZ=Asia/Ho_Chi_Minh

FROM base
WORKDIR /build
COPY receiver/ .
RUN go build -o receiver
CMD ["/build/receiver"]
