FROM docker.io/golang:1.24.2-alpine3.21 as base
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY utils ./utils
COPY service ./service
ENV TZ=Asia/Ho_Chi_Minh

FROM base
COPY cmd/sender .
RUN go build -o sender
CMD ["/build/sender"]
